name: CD
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  python-packaging:
    name: 🐍 Packaging
    uses: ./.github/workflows/reusable-python-packaging.yml
    with:
      package-name: mqt.core
