name: 🇨 • Tests • macos-latest
on:
  workflow_call:
    inputs:
      config:
        description: "The configuration to use (Debug or Release)"
        required: true
        type: string

jobs:
  cpp-tests-macos:
    name: 🍎 ${{ inputs.config }}
    runs-on: macos-latest
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 3
      CTEST_PARALLEL_LEVEL: 3
      FORCE_COLOR: 3
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          prepend_symlinks_to_path: false
          override_cache_key: c++-tests-macos-latest-${{ inputs.config }}
      - name: Install Ninja
        run: pipx install ninja
      - name: Configure CMake
        run: cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=${{ inputs.config }}
      - name: Build
        run: cmake --build build --config ${{ inputs.config }}
      - name: Test
        run: ctest -C ${{ inputs.config }} --output-on-failure --test-dir build --repeat until-pass:3 --timeout 300
