name: 🐍 • Lint
on:
  workflow_call:

jobs:
  lint:
    name: 🚨 Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          prepend_symlinks_to_path: false
          override_cache_key: lint
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Set up mold as linker (Linux only)
        uses: rui314/setup-mold@v1
      - name: Run PyLint
        run: |
          echo "::add-matcher::${{ github.workspace }}/.github/matchers/pylint.json"
          pipx run nox -s pylint
