name: 📝 • CodeQL • Python
on:
  workflow_call:

jobs:
  analyze:
    name: 🐍 Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          prepend_symlinks_to_path: false
          override_cache_key: codeql-cpp
      - name: Set up mold as linker
        uses: rui314/setup-mold@v1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install nanobind scikit-build-core[pyproject] setuptools_scm pybind11
          pip install --no-build-isolation -ve .
          echo "CODEQL_PYTHON=$(which python)" >> $GITHUB_ENV
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
          config-file: .github/codeql-config.yml
          setup-python-dependencies: false
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          upload: False
          output: sarif-results
      - name: filter-sarif
        uses: advanced-security/filter-sarif@main
        with:
          patterns: |
            -**/extern/**
          input: sarif-results/python.sarif
          output: sarif-results/python.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif-results/python.sarif
